spring:
  application:
    name: person-service
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
server:
  address: '0.0.0.0'
  port: 10021